name: modelday_frontend
description: ModelDay Frontend - Flutter web application for models, photographers, and industry professionals
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Material Design
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Routing
  go_router: ^12.1.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # JSON and Serialization
  json_annotation: ^4.8.1
  
  # UI Components and Utilities
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Animations
  lottie: ^2.7.0
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.1
  
  # Web specific
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

# Web configuration
flutter_web:
  auto_detect_web: true
